---
layout: cv
title: Preston Sagastegui Resume
---
# Preston Sagastegui
Marketing Consultant, Product Management, Data Science.

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Standing on the shoulders of giants

### Specialized in

Business Analytics and Data Science

## Education

`September 2020 - Present`
__Brigham Young University, Idaho__

## Projects

`January 2025 - Present`
__Data Science Society__, Rexburg, Idaho

- Manage and optimize databases, performing data cleaning, transformation and ETL processes using SQL and Python to improve AI-driven truck routing with Ollama AI and Fleetbase
- Develop and automate AI-driven workflows (Ollama LLM) with prompt engineering, enhancing predictive analytics, route optimization, and UI/UX integration for improved decision making

`January 2025 - Present`
__SubLens Independent Project__, Rexburg, Idaho

- •	Engineering  AI-powered smart glasses integrating NLP (PyTorch, OpenAI Whisper, Google Translate API) with AR text overlay achieving real-time multilingual translation with a sub-1-second latency 

## Experience

`February 2023 - Present`
__Freelance Digital Marketing Consulant__, Hybrid

- Optimized and managed ad accounts for Gameday Men’s Health & Solomon Law Group, increasing lead conversions by 30% with A/B testing, audience segmentation and automation
- Automated lead management with Zapier and CRM integrations, reducing contact time by 99%
- Consulted on growth strategies for 15+ businesses, managing $2k+ monthly ad budgets, optimizing campaigns, and creating data-driven content for higher engagement and ROI

`February 2023 - Present`
__General Manager__, Cocomo Confections

- Optimized website UX/UI and landing pages SEO, driving a 25% sales increase in 3 months
- Implemented data-driven digital marketing strategies, resulting in a 94% increase in customer base
- Conducted in-depth statistical analysis and created data visualizations to inform strategic business decisions improving forecasting accuracy by 25%


<!-- ### Footer

Last updated: March 2025 -->